import { load } from 'js-yaml';

export interface ValidationError {
  line: number;
  column?: number;
  message: string;
  rule: string;
  severity: 'error' | 'warning';
}

export interface ValidationWarning {
  line?: number;
  message: string;
  suggestion?: string;
}

export interface ValidationStats {
  lines: number;
  jobsCount: number;
  stepsCount: number;
  triggers: string[];
  secrets: string[];
  runners: string[];
}

export interface ValidationResult {
  isValid: boolean;
  errors: ValidationError[];
  warnings: ValidationWarning[];
  stats: ValidationStats;
  parsed: Record<string, any> | null;
}

export interface SuggestionItem {
  prefix: string;
  label: string;
  snippet: string;
  description: string;
  category: 'directive' | 'runner' | 'action' | 'trigger' | 'expression' | 'strategy';
  iconName?: string;
}

/**
 * Common GitHub Actions autocompletion suggestions library
 */
export const GITHUB_ACTIONS_SUGGESTIONS: SuggestionItem[] = [
  // Directives
  {
    prefix: 'name',
    label: 'name: Workflow Name',
    snippet: 'name: CI/CD Pipeline\n',
    description: 'The name of your workflow. GitHub displays it in the Actions tab.',
    category: 'directive',
  },
  {
    prefix: 'on',
    label: 'on: [push, pull_request]',
    snippet: 'on:\n  push:\n    branches: [main]\n  pull_request:\n    branches: [main]\n',
    description: 'Trigger the workflow on push or pull request to main branch.',
    category: 'trigger',
  },
  {
    prefix: 'jobs',
    label: 'jobs: Pipeline Jobs',
    snippet: 'jobs:\n  build:\n    name: Build & Test\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n',
    description: 'Defines the set of jobs to be executed in this workflow.',
    category: 'directive',
  },
  {
    prefix: 'runs-on',
    label: 'runs-on: ubuntu-latest',
    snippet: 'runs-on: ubuntu-latest',
    description: 'Standard Linux x64 virtual environment provided by GitHub.',
    category: 'runner',
  },
  {
    prefix: 'runs-on-win',
    label: 'runs-on: windows-latest',
    snippet: 'runs-on: windows-latest',
    description: 'Windows Server 2022 runner VM provided by GitHub.',
    category: 'runner',
  },
  {
    prefix: 'runs-on-mac',
    label: 'runs-on: macos-latest',
    snippet: 'runs-on: macos-latest',
    description: 'macOS runner VM provided by GitHub (Apple Silicon/M1).',
    category: 'runner',
  },
  {
    prefix: 'steps',
    label: 'steps: Job Steps',
    snippet: 'steps:\n  - name: Checkout repository\n    uses: actions/checkout@v4\n  - name: Run command\n    run: echo "Hello World"\n',
    description: 'A sequence of tasks that make up a job.',
    category: 'directive',
  },
  // Actions
  {
    prefix: 'checkout',
    label: 'uses: actions/checkout@v4',
    snippet: '- name: Checkout repository\n  uses: actions/checkout@v4\n  with:\n    fetch-depth: 0\n',
    description: 'Checks out your repository under $GITHUB_WORKSPACE so your workflow can access it.',
    category: 'action',
  },
  {
    prefix: 'setup-node',
    label: 'uses: actions/setup-node@v4',
    snippet: '- name: Set up Node.js\n  uses: actions/setup-node@v4\n  with:\n    node-version: 20\n    cache: npm\n',
    description: 'Sets up a Node.js environment and configures npm/yarn/pnpm caching.',
    category: 'action',
  },
  {
    prefix: 'setup-python',
    label: 'uses: actions/setup-python@v5',
    snippet: '- name: Set up Python\n  uses: actions/setup-python@v5\n  with:\n    python-version: "3.11"\n    cache: pip\n',
    description: 'Sets up a Python environment and adds python to PATH.',
    category: 'action',
  },
  {
    prefix: 'setup-go',
    label: 'uses: actions/setup-go@v5',
    snippet: '- name: Set up Go\n  uses: actions/setup-go@v5\n  with:\n    go-version: "^1.22"\n    cache: true\n',
    description: 'Sets up a Go programming environment.',
    category: 'action',
  },
  {
    prefix: 'cache',
    label: 'uses: actions/cache@v4',
    snippet: '- name: Cache dependencies\n  uses: actions/cache@v4\n  with:\n    path: ~/.npm\n    key: ${{ runner.os }}-node-${{ hashFiles(\'**/package-lock.json\') }}\n    restore-keys: |\n      ${{ runner.os }}-node-\n',
    description: 'Cache dependencies and build outputs across workflow runs.',
    category: 'action',
  },
  {
    prefix: 'upload-artifact',
    label: 'uses: actions/upload-artifact@v4',
    snippet: '- name: Upload build artifact\n  uses: actions/upload-artifact@v4\n  with:\n    name: release-build\n    path: dist/\n    retention-days: 7\n',
    description: 'Upload files generated by your workflow so they can be downloaded.',
    category: 'action',
  },
  {
    prefix: 'download-artifact',
    label: 'uses: actions/download-artifact@v4',
    snippet: '- name: Download build artifact\n  uses: actions/download-artifact@v4\n  with:\n    name: release-build\n    path: dist/\n',
    description: 'Download artifacts previously uploaded during this workflow run.',
    category: 'action',
  },
  {
    prefix: 'docker-build',
    label: 'uses: docker/build-push-action@v5',
    snippet: '- name: Build and push Docker image\n  uses: docker/build-push-action@v5\n  with:\n    context: .\n    push: true\n    tags: user/app:latest\n',
    description: 'Build and push Docker images using Buildx.',
    category: 'action',
  },
  // Triggers
  {
    prefix: 'workflow_dispatch',
    label: 'workflow_dispatch: Manual trigger',
    snippet: 'workflow_dispatch:\n  inputs:\n    environment:\n      description: "Target environment to deploy"\n      required: true\n      default: "staging"\n',
    description: 'Allows manual execution of this workflow from the GitHub Actions web UI.',
    category: 'trigger',
  },
  {
    prefix: 'schedule',
    label: 'schedule: Cron schedule',
    snippet: 'schedule:\n  - cron: "0 0 * * *"\n',
    description: 'Schedule this workflow to run periodically (e.g. daily at midnight UTC).',
    category: 'trigger',
  },
  // Strategies & Environment
  {
    prefix: 'matrix',
    label: 'strategy: matrix: Multi-version test',
    snippet: 'strategy:\n  matrix:\n    os: [ubuntu-latest, macos-latest]\n    node-version: [18, 20, 22]\n',
    description: 'Run multiple job permutations across operating systems and language versions.',
    category: 'strategy',
  },
  {
    prefix: 'permissions',
    label: 'permissions: read-all / contents: read',
    snippet: 'permissions:\n  contents: read\n  packages: write\n',
    description: 'Restrict default GITHUB_TOKEN permissions for improved supply-chain security.',
    category: 'directive',
  },
  {
    prefix: 'env',
    label: 'env: Environment Variables',
    snippet: 'env:\n  NODE_ENV: production\n  CI: true\n',
    description: 'Set environment variables accessible to all steps or jobs.',
    category: 'directive',
  },
  {
    prefix: 'secret',
    label: '${{ secrets.SECRET_NAME }}',
    snippet: '${{ secrets.GITHUB_TOKEN }}',
    description: 'Reference an encrypted secret configured in your repository settings.',
    category: 'expression',
  },
  {
    prefix: 'needs',
    label: 'needs: [build]',
    snippet: 'needs: [build]\n',
    description: 'Creates a dependency where this job runs only after specified jobs succeed.',
    category: 'directive',
  },
  {
    prefix: 'if',
    label: 'if: github.ref == \'refs/heads/main\'',
    snippet: 'if: github.ref == \'refs/heads/main\' && github.event_name == \'push\'\n',
    description: 'Conditional expression to determine whether a job or step should run.',
    category: 'expression',
  },
];

/**
 * Validates a GitHub Actions workflow YAML string.
 * Performs YAML syntax validation, schema integrity checks, security warnings, and stats extraction.
 */
export function validateWorkflowYaml(yamlContent: string): ValidationResult {
  const errors: ValidationError[] = [];
  const warnings: ValidationWarning[] = [];
  const stats: ValidationStats = {
    lines: 0,
    jobsCount: 0,
    stepsCount: 0,
    triggers: [],
    secrets: [],
    runners: [],
  };

  const rawLines = yamlContent.split('\n');
  stats.lines = rawLines.length;

  if (!yamlContent.trim()) {
    errors.push({
      line: 1,
      message: 'Workflow YAML is empty. Enter valid GitHub Actions workflow code.',
      rule: 'empty-document',
      severity: 'error',
    });
    return {
      isValid: false,
      errors,
      warnings,
      stats,
      parsed: null,
    };
  }

  // 1. Check for tab characters (illegal in YAML indentation)
  rawLines.forEach((line, idx) => {
    if (line.includes('\t')) {
      errors.push({
        line: idx + 1,
        column: line.indexOf('\t') + 1,
        message: 'Tab character found. YAML indentation must use spaces, never tabs.',
        rule: 'no-tabs',
        severity: 'error',
      });
    }
  });

  // 2. Check for unclosed expression brackets ${{ without }}
  rawLines.forEach((line, idx) => {
    if (line.includes('${{') && !line.includes('}}')) {
      errors.push({
        line: idx + 1,
        column: line.indexOf('${{') + 1,
        message: 'Unclosed GitHub Actions expression. Found "${{" without matching "}}".',
        rule: 'expression-syntax',
        severity: 'error',
      });
    }
  });

  // 3. Scan for referenced secrets
  const secretRegex = /secrets\.([a-zA-Z0-9_]+)/g;
  let secretMatch: RegExpExecArray | null;
  const uniqueSecrets = new Set<string>();
  while ((secretMatch = secretRegex.exec(yamlContent)) !== null) {
    if (secretMatch[1]) {
      uniqueSecrets.add(secretMatch[1]);
    }
  }
  stats.secrets = Array.from(uniqueSecrets);

  // 4. Parse YAML structure with js-yaml
  let parsed: any = null;
  try {
    parsed = load(yamlContent);
  } catch (err: any) {
    const line = err?.mark?.line !== undefined ? err.mark.line + 1 : 1;
    const column = err?.mark?.column !== undefined ? err.mark.column + 1 : 1;
    const cleanReason = err?.reason || err?.message || 'Invalid YAML syntax';

    errors.push({
      line,
      column,
      message: `YAML Syntax Error: ${cleanReason}`,
      rule: 'yaml-syntax',
      severity: 'error',
    });

    return {
      isValid: false,
      errors,
      warnings,
      stats,
      parsed: null,
    };
  }

  // 5. Schema Validation for GitHub Actions
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    errors.push({
      line: 1,
      message: 'Workflow root must be an object/mapping with keys like "name", "on", and "jobs".',
      rule: 'root-object',
      severity: 'error',
    });
    return {
      isValid: false,
      errors,
      warnings,
      stats,
      parsed: null,
    };
  }

  // Check 'name'
  if (!parsed.name) {
    warnings.push({
      line: 1,
      message: 'Consider adding a top-level "name:" field to easily identify this workflow in GitHub Actions.',
      suggestion: 'name: CI/CD Pipeline',
    });
  }

  // Check 'on' triggers (in YAML 1.1, 'on:' can parse as key 'on' or boolean true)
  const hasOn = parsed.on !== undefined || parsed[true as any] !== undefined;
  if (!hasOn) {
    errors.push({
      line: 1,
      message: 'Missing required root property "on:" to specify workflow triggers (e.g. push, pull_request).',
      rule: 'missing-on',
      severity: 'error',
    });
  } else {
    const onVal = parsed.on !== undefined ? parsed.on : parsed[true as any];
    if (typeof onVal === 'string') {
      stats.triggers = [onVal];
    } else if (Array.isArray(onVal)) {
      stats.triggers = onVal.map(String);
    } else if (typeof onVal === 'object' && onVal !== null) {
      stats.triggers = Object.keys(onVal);
    }
  }

  // Check 'jobs'
  if (!parsed.jobs) {
    errors.push({
      line: 1,
      message: 'Missing required root property "jobs:". A workflow must define at least one job.',
      rule: 'missing-jobs',
      severity: 'error',
    });
  } else if (typeof parsed.jobs !== 'object' || Array.isArray(parsed.jobs)) {
    errors.push({
      line: findLineNumberForKey(rawLines, 'jobs'),
      message: 'The "jobs:" property must be a mapping of job IDs to job definitions.',
      rule: 'invalid-jobs-type',
      severity: 'error',
    });
  } else {
    const jobKeys = Object.keys(parsed.jobs);
    stats.jobsCount = jobKeys.length;

    if (jobKeys.length === 0) {
      errors.push({
        line: findLineNumberForKey(rawLines, 'jobs'),
        message: 'The "jobs:" property is empty. Define at least one job (e.g. "build:").',
        rule: 'empty-jobs',
        severity: 'error',
      });
    }

    // Validate each job
    jobKeys.forEach((jobId) => {
      const job = parsed.jobs[jobId];
      const jobLine = findLineNumberForKey(rawLines, jobId);

      if (!/^[a-zA-Z_][a-zA-Z0-9_-]*$/.test(jobId)) {
        errors.push({
          line: jobLine,
          message: `Invalid job identifier "${jobId}". Job IDs must start with a letter or underscore and contain only alphanumeric characters, "-", or "_".`,
          rule: 'invalid-job-id',
          severity: 'error',
        });
      }

      if (!job || typeof job !== 'object' || Array.isArray(job)) {
        errors.push({
          line: jobLine,
          message: `Job "${jobId}" must be an object defining "runs-on" and "steps" or "uses".`,
          rule: 'invalid-job-def',
          severity: 'error',
        });
        return;
      }

      // Reusable workflow calls use 'uses' at the job level
      const isReusableCall = Boolean(job.uses);

      if (!isReusableCall) {
        if (!job['runs-on']) {
          errors.push({
            line: jobLine,
            message: `Job "${jobId}" is missing the required "runs-on:" field (e.g. "runs-on: ubuntu-latest").`,
            rule: 'missing-runs-on',
            severity: 'error',
          });
        } else {
          const runner = String(job['runs-on']);
          if (!stats.runners.includes(runner)) {
            stats.runners.push(runner);
          }
        }

        if (!job.steps) {
          errors.push({
            line: jobLine,
            message: `Job "${jobId}" is missing "steps:". Add steps to execute commands or actions.`,
            rule: 'missing-steps',
            severity: 'error',
          });
        } else if (!Array.isArray(job.steps)) {
          errors.push({
            line: jobLine,
            message: `The "steps:" property in job "${jobId}" must be a sequence of step items.`,
            rule: 'invalid-steps-type',
            severity: 'error',
          });
        } else {
          stats.stepsCount += job.steps.length;

          if (job.steps.length === 0) {
            warnings.push({
              line: jobLine,
              message: `Job "${jobId}" has an empty "steps:" list.`,
            });
          }

          // Validate individual steps
          job.steps.forEach((step: any, stepIdx: number) => {
            if (!step || typeof step !== 'object') {
              errors.push({
                line: jobLine,
                message: `Job "${jobId}" step #${stepIdx + 1} must be an object.`,
                rule: 'invalid-step',
                severity: 'error',
              });
              return;
            }

            if (!step.run && !step.uses) {
              errors.push({
                line: jobLine,
                message: `Job "${jobId}" step #${stepIdx + 1}${step.name ? ` ("${step.name}")` : ''} must have either a "run:" or "uses:" attribute.`,
                rule: 'step-run-or-uses',
                severity: 'error',
              });
            }

            // Check unpinned actions (@main or @master)
            if (step.uses && typeof step.uses === 'string') {
              if (step.uses.endsWith('@main') || step.uses.endsWith('@master')) {
                warnings.push({
                  line: jobLine,
                  message: `Action "${step.uses}" uses a moving branch tag (@main/@master). Pin to a version tag (e.g. @v4) or full commit SHA for reproducibility.`,
                  suggestion: `${step.uses.split('@')[0]}@v4`,
                });
              }
            }
          });
        }
      }
    });
  }

  // Security Check: Permissions
  if (!parsed.permissions) {
    warnings.push({
      line: 1,
      message: 'No top-level "permissions:" block detected. Best practice recommends setting "permissions: read-all" or "permissions: contents: read" to harden against privilege escalation.',
      suggestion: 'permissions:\n  contents: read',
    });
  }

  return {
    isValid: errors.length === 0,
    errors,
    warnings,
    stats,
    parsed,
  };
}

/**
 * Finds approximate 1-indexed line number for a specific YAML key.
 */
function findLineNumberForKey(lines: string[], key: string): number {
  const pattern = new RegExp(`^\\s*${escapeRegExp(key)}\\s*:`);
  for (let i = 0; i < lines.length; i++) {
    if (pattern.test(lines[i])) {
      return i + 1;
    }
  }
  return 1;
}

function escapeRegExp(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Computes autocomplete suggestions based on current word / token being typed.
 */
export function getSuggestionsForInput(
  currentLine: string,
  wordPrefix: string
): SuggestionItem[] {
  const cleanPrefix = wordPrefix.trim().toLowerCase();
  if (!cleanPrefix) {
    return GITHUB_ACTIONS_SUGGESTIONS.slice(0, 8);
  }

  return GITHUB_ACTIONS_SUGGESTIONS.filter((s) => {
    return (
      s.prefix.toLowerCase().includes(cleanPrefix) ||
      s.label.toLowerCase().includes(cleanPrefix) ||
      s.category.toLowerCase().includes(cleanPrefix) ||
      s.description.toLowerCase().includes(cleanPrefix)
    );
  });
}
